export const GET_ALL = 'posts_get_all'
export const UPDATE = 'posts_update'
export const LOADING = 'posts_loading'
export const ERROR = 'posts_error'
export const COMMENTS_UPDATE = 'post_comments_update'
export const COMMENTS_LOADING = 'posts_comments_loading'
export const COMMENTS_ERROR = 'posts_comments_error'